import Header from './Components/Header'
import { CounterContextProvider } from './context/cartItems.context';
import './globals.css'
import './styles/font.css';

import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
    <html lang="en">
    
      <body className='m-0 p-0'>
      <CounterContextProvider>
      <Header/>
        {children}
        </CounterContextProvider>
        </body>
       
    </html>
  )
}
